[tool.poetry]
name = "failures-analysis"
version = "0.1.0"
description = "Tests failure analysis package provides fast and reliable way to find and group similar failures in your CI/CD pipeline. When failure grouping and similarity scoring is done automatically by a machine, it will free resources from development team member to fix the most important failures in their CI/CD pipeline. It is tedious work for a human to download, open and read all the test failures and analyse which failures belong to the same group. The failure-analysis package solves this problem by processing xunit xml files and using XXXXXX to find similar failures from the test results."
authors = ["Tatu Aalto"]
license = "Apache-2.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Testing",
]
packages = [
    { include = "failure_analysis", from="."}
]

[tool.poetry.scripts]
failure_analysis = "failure_analysis.failure_analysis:main"

[tool.poetry.dependencies]
python = "^3.8"
jellyfish = "^0.9.0"
numpy = "^1.22.4"
pandas = "^1.4.2"
sklearn = "^0.0"
lxml = "^4.8.0"
python-Levenshtein = "^0.12.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.3.0"
isort = "^5.10.1"
invoke = "^1.7.1"
mypy = "^0.960"
flake8 = "^4.0.1"
python-semantic-release = "^7.29.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py38']

[tool.semantic_release]
version_toml  = [
    "pyproject.toml:tool.poetry.version",
    "failure_analysis/__init__.py:__version__"
]
