# This is a basic workflow to help you get started with Actions

name: CICD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  check:
    name: Check commit message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check commit message
        uses: adityaa30/check-commit@master
        with:
          max-header-length: 255
